Repository unoplat/unoplat-code-confluence, pull requests merged in 2024-12, with the labels that each got.

#210 added company logo
  code-confluence/docusaurus.config.js
  code-confluence/src/components/Footer/index.js
  code-confluence/src/css/custom.css
  code-confluence/static/img/unoplat_logo.png
Labels: Review effort [1-5]: 1

#219 218 chore remove unwanted dspy old files
  unoplat-code-confluence/.isort.cfg
  unoplat-code-confluence/tests/confluence_git/test_github_helper.py
  unoplat-code-confluence/tests/parser/python/function_metadata/test_function_metadata_parser.py
  unoplat-code-confluence/tests/parser/python/in_class_dependency/test_sort_function_dependencies.py
  unoplat-code-confluence/tests/parser/python/node_variables/test_node_variables_parser.py
  unoplat-code-confluence/tests/parser/python/test_python_import_segregation_strategy.py
  unoplat-code-confluence/tests/utility/test_is_class_name.py
  unoplat-code-confluence/unoplat_code_confluence/__main__.py
  unoplat-code-confluence/unoplat_code_confluence/configuration/external_config.py
  unoplat-code-confluence/unoplat_code_confluence/configuration/settings.py
  unoplat-code-confluence/unoplat_code_confluence/confluence_git/github_helper.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi/chapi_functioncall.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_forge/unoplat_chapi_forge_node.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_forge/unoplat_import.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_forge/unoplat_package.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_unoplat_annotation.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_unoplat_class_fieldmodel.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_unoplat_codebase.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_unoplat_function.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_unoplat_import.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_unoplat_node.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_unoplat_parameter.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/dspy/dspy_unoplat_node_summary.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/forge_summary/forge_unoplat_codebase_summary.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/forge_summary/forge_unoplat_function_summary.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/forge_summary/forge_unoplat_package_summary.py
  unoplat-code-confluence/unoplat_code_confluence/data_models/unoplat_function_field_model.py
  unoplat-code-confluence/unoplat_code_confluence/downloader/downloader.py
  unoplat-code-confluence/unoplat_code_confluence/dspy_class_summary.py
  unoplat-code-confluence/unoplat_code_confluence/dspy_codebase_summary.py
  unoplat-code-confluence/unoplat_code_confluence/dspy_function_summary.py
  unoplat-code-confluence/unoplat_code_confluence/dspy_package_summary.py
  unoplat-code-confluence/unoplat_code_confluence/loader/iparse_json.py
  unoplat-code-confluence/unoplat_code_confluence/loader/parse_json.py
  unoplat-code-confluence/unoplat_code_confluence/markdownparser/isummariser.py
  unoplat-code-confluence/unoplat_code_confluence/markdownparser/markdownsummariser.py
  unoplat-code-confluence/unoplat_code_confluence/parser/python/function_metadata/function_metadata_parser.py
  unoplat-code-confluence/unoplat_code_confluence/parser/python/in_class_dependency/sort_function_dependencies.py
  unoplat-code-confluence/unoplat_code_confluence/parser/python/node_variables/node_variables_parser.py
  unoplat-code-confluence/unoplat_code_confluence/parser/python/package_manager/utils/setup_parser.py
  unoplat-code-confluence/unoplat_code_confluence/parser/python/python_extract_inheritance.py
  unoplat-code-confluence/unoplat_code_confluence/parser/python/python_node_dependency_processor.py
  unoplat-code-confluence/unoplat_code_confluence/parser/tree_sitter/code_confluence_tree_sitter.py
  unoplat-code-confluence/unoplat_code_confluence/utility/is_class_name.py
  unoplat-code-confluence/unoplat_code_confluence/utility/total_file_count.py
Labels: documentation, enhancement

#226 225 docs update setup run and example instructions in documentation website
  code-confluence/docs/deep-dive/_category_.json
  code-confluence/docs/deep-dive/vision.md
  code-confluence/docs/quickstart/how-to-run.md
  code-confluence/docs/unoplat-oss-atlas/import-codebase.md
  code-confluence/yarn.lock
  unoplat-code-confluence/example_config_code_confluence_current.json
  unoplat-code-confluence/pyproject.toml
  unoplat-code-confluence/unoplat_code_confluence/__main__.py
  unoplat-code-confluence/unoplat_code_confluence/configuration/settings.py
Labels: documentation
