Repository unoplat/unoplat-code-confluence, pull requests merged in 2024-10, with the labels that each got.

#120 53 feature enable knowledge graph ingestion
  .github/configuration/release-please-config.json
  .github/configuration/release-please-manifest.json
  .github/workflows/python_build.yaml
  .gitignore
  unoplat-code-confluence-query-engine/README.md
  unoplat-code-confluence-query-engine/dspy/__init__.py
  unoplat-code-confluence-query-engine/dspy/dspy_init.py
  unoplat-code-confluence-query-engine/experiment_graph_cypher_query.ipynb
  unoplat-code-confluence-query-engine/pyproject.toml
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/__init__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/__main__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/configuration/__init__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/configuration/external_config.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/embedding/__init__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/embedding/unoplat_embedding_generator.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/embedding/unoplat_rerank_embedding.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/graph/__init__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/graph/neo4j_helper.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/helper/__init__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/helper/ijson_loader.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/helper/json_loader.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/models/__init__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/models/confluence_codebase.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/models/confluence_func_hiearchy.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/models/confluence_package.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/models/confluence_user_intent.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/processing/__init__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/processing/query_engine_process.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/screens/__init__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/screens/chat_screen.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/unoplat_dspy/__init__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/unoplat_dspy/intent_detection_module.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/unoplat_dspy/user_query_based_rererank_module.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/unoplat_dspy/user_query_final_response.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/widgets/__init__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/widgets/chat_history.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/widgets/unoplat_chat.py
  unoplat-code-confluence/pyproject.toml
  unoplat-code-confluence/unoplat_code_confluence/__main__.py
  unoplat-code-confluence/unoplat_code_confluence/configuration/external_config.py
  unoplat-code-confluence/unoplat_code_confluence/database/__init__.py
  unoplat-code-confluence/unoplat_code_confluence/database/graph/__init__.py
  unoplat-code-confluence/unoplat_code_confluence/database/graph/unoplat_graph_ingestion.py
  unoplat-code-confluence/unoplat_code_confluence/database/graph/unoplat_graph_processing.py
  unoplat-code-confluence/unoplat_code_confluence/dspy_class_summary.py
  unoplat-code-confluence/unoplat_code_confluence/embedding/__init__.py
  unoplat-code-confluence/unoplat_code_confluence/embedding/unoplat_embedding_gen.py
Labels: enhancement

#131 docs: updated main features of unoplat code confluence
  code-confluence/docs/deep-dive/_category_.json
  code-confluence/src/components/HomepageFeatures/index.js
Labels: documentation

#136 134 tui support ondemand retrieval of graph data of oss codebases
  .github/workflows/docs_deploy.yaml
  .gitignore
  scripts/export_data_graph.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/__main__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/graph/neo4j_helper.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/processing/query_engine_process.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/query_engine_style.tcss
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/screens/chat_screen.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/screens/codebase_options.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/screens/existing_codebase_list.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/screens/graph_load_progress_screen.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/widgets/json_directory_tree.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/widgets/unoplat_chat.py
Labels: enhancement

#139 chore: changed label for app and disabled placeholder for chat histor…
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/__main__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/query_engine_style.tcss
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/screens/chat_screen.py
Labels: enhancement

#141 fix: bug fix for poetry script
  unoplat-code-confluence/pyproject.toml
  unoplat-code-confluence/unoplat_code_confluence/__main__.py
Labels: bug

#149 docs: improved docs
  code-confluence/docs/quickstart/how-to-run.md
  code-confluence/docs/quickstart/installation.md
  code-confluence/docs/unoplat-oss-atlas/_category_.json
  code-confluence/docs/unoplat-oss-atlas/import-codebase.md
  code-confluence/docs/unoplat-oss-atlas/links.md
  code-confluence/docs/unoplat-oss-atlas/why.md
  code-confluence/docusaurus.config.js
  code-confluence/package.json
  code-confluence/src/css/custom.css
  code-confluence/static/img/code-confluence-existing-codebases.png
  code-confluence/static/img/code-confluence-neo4j-browser.png
  code-confluence/static/img/code-confluence-parsing-ingestion.png
  code-confluence/static/img/code-confluence-query-engine.png
  code-confluence/yarn.lock
Labels: enhancement

#155 completed contact us screen
  code-confluence/package-lock.json
  code-confluence/package.json
  code-confluence/src/css/contact-us.module.css
  code-confluence/src/pages/contact-us.js
  code-confluence/yarn.lock
Labels: enhancement, dependencies, Review effort [1-5]: 3

#158 removed unwanted component from website and implement search functionality
  code-confluence/docs/index.md
  code-confluence/docusaurus.config.js
  code-confluence/package-lock.json
  code-confluence/src/components/Footer/index.js
  code-confluence/src/components/HomepageFeatures/styles.module.css
  code-confluence/src/css/contact-us.module.css
  code-confluence/src/pages/contact-us.js
  code-confluence/src/pages/features.js
  code-confluence/yarn.lock
Labels: documentation, enhancement, Review effort [1-5]: 3

#161 160 feat change the vector search to implementation summary
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/__main__.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/graph/neo4j_helper.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/models/confluence_class.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/models/confluence_user_intent.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/processing/query_engine_process.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/unoplat_dspy/intent_detection_module.py
Labels: bug, enhancement

#164 163 improve summarisation of reranked results
  .gitignore
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/unoplat_dspy/user_query_final_response.py
  unoplat-code-confluence/poetry.lock
  unoplat-code-confluence/pyproject.toml
  unoplat-code-confluence/unoplat_code_confluence/data_models/chapi_unoplat_class_summary.py
Labels: enhancement

#167 feat: added common lib for ingestion and query utility
  .github/configuration/release-please-config.json
  .github/workflows/python_build.yaml
  .github/workflows/python_publish_release_management.yaml
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/__init__.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/__init__.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/base_models.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/class_node.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/codebase_node.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/method_node.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/package_node.py
Labels: enhancement

#175 fix: add float type to array property to hold vector indexes properly
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/class_node.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/codebase_node.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/method_node.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/package_node.py
Labels: enhancement

#178 fix: removed vector indexes and renamed properly to ensure right dime…
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/class_node.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/codebase_node.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_class.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_codebase.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_method.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_package.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/method_node.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/package_node.py
Labels: enhancement

#182 fix: removed default as required is true
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_package.py
Labels: bug

#184 181 bug default and required properties in neomodel
  .gitignore
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_class.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_codebase.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_method.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_package.py
Labels: enhancement

#186 fix: enable bidirectional cardinality
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_class.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_codebase.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_method.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_package.py
Labels: enhancement

#188 fix: relationships from and to codebase, packages, classes and method…
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_class.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_codebase.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_method.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_package.py
Labels: bug, enhancement

#192 fix: simplifying the names
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_class.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_codebase.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_method.py
  unoplat-code-confluence-commons/unoplat_code_confluence_commons/graph_models/confluence_package.py
Labels: bug, enhancement

#190 feat: moved from native cypher to neomodel and it feels at home
  scripts/export_data_graph.py
  unoplat-code-confluence-query-engine/poetry.lock
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/embedding/unoplat_embedding_generator.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/graph/neo4j_helper.py
  unoplat-code-confluence-query-engine/unoplat_code_confluence_query_engine/processing/query_engine_process.py
  unoplat-code-confluence/poetry.lock
  unoplat-code-confluence/pyproject.toml
  unoplat-code-confluence/unoplat_code_confluence/data_models/dspy/dspy_unoplat_fs_annotation_subset.py
  unoplat-code-confluence/unoplat_code_confluence/database/graph/unoplat_graph_ingestion.py
  unoplat-code-confluence/unoplat_code_confluence/database/graph/unoplat_graph_processing.py
  unoplat-code-confluence/unoplat_code_confluence/downloader/downloader.py
  unoplat-code-confluence/unoplat_code_confluence/dspy_codebase_summary.py
  unoplat-code-confluence/unoplat_code_confluence/embedding/unoplat_embedding_gen.py
Labels: enhancement
